### ISSUE TITLE
Add margins to cards, reduce size on various items

### ISSUE THREAD

**Issue by longview-labs** [nicholasoxford/welcome-to-the-weave#7]
Thought I had posted this already, looks like it didn't 🙃

The current site has cards a bit large - they also expand too much when on larger screens and need to have a max size. 

Please see notes below:

<img width="1266" alt="Screen Shot 2021-10-31 at 9 54 12 AM" src="https://user-images.githubusercontent.com/91092010/140655133-d694ce08-12c6-4218-96e4-b27a0c03d92d.png">

Figma design:

<img width="1280" alt="figma design" src="https://user-images.githubusercontent.com/91092010/140655149-6421143b-6097-4688-b5a3-69ecb1561324.png">

**Comment by mdvb1001** [comment]
@everythingarweave @nicholasoxford 
Next wave of styling enhancements. Let me know what you think

![image](https://user-images.githubusercontent.com/20603793/141923502-da3394da-06df-4a70-8598-5d2a213388c4.png)

**Comment by longview-labs** [comment]
Beautiful! If you can widen the upper text area for the "Get the ArConnect" area for each of the cards that is 👌. Also, #2 upper text looks to be a bit lower than the others. Ideally, they're all the same throughout.
